import { Sun, Waves, CloudRain, Flame, Moon, Zap, Sparkles, Wind, Droplets, ShieldAlert, BedDouble, Activity } from 'lucide-react';

export const MOODS = [
  {
    id: 'happy',
    label: 'Happy',
    emoji: '😊',
    icon: Sun,
    altIcon: Sparkles,
    statusTag: 'Sunlit Radiance',
    description: 'Radiant, grateful & uplifted',
    message: 'Bask in the warmth of this uplifting moment. Let joy guide your space.',
    experienceMessage: 'Your spirit is glowing with warmth. Celebrate this lightness of being, share your positive energy, and let this radiant frequency expand into every corner of your day.',
    particleType: 'bubbles',
    breathingPace: 3.5,
    accent: {
      border: 'border-amber-300/60',
      bgSelected: 'bg-amber-400/20',
      glow: 'shadow-amber-500/30',
      badge: 'bg-amber-400/30 text-amber-200 border-amber-300/50',
      iconColor: 'text-amber-300',
    },
    environment: {
      // Full-viewport warm, cheerful golden/amber atmosphere
      bgBase: 'from-[#331c03] via-[#522e03] to-[#241300]',
      primaryGlow: 'from-amber-400/40 via-yellow-400/30 to-orange-500/25',
      secondaryGlow: 'from-orange-400/35 via-amber-300/25 to-yellow-500/15',
      accentRing: 'border-amber-300/60 text-amber-200',
      pulseColor: '#f59e0b',
      buttonGradient: 'from-amber-500 via-yellow-500 to-orange-500',
      cardBorder: 'border-amber-400/30',
      cardBg: 'bg-[#291602]/60',
      headerBg: 'bg-[#291602]/40',
    },
  },
  {
    id: 'calm',
    label: 'Calm',
    emoji: '😌',
    icon: Waves,
    altIcon: Wind,
    statusTag: 'Serene Sanctuary',
    description: 'Peaceful, balanced & centered',
    message: 'Take a moment to slow down and breathe.',
    experienceMessage: 'Inhale stillness, exhale hurry. You are grounded in this quiet aquatic sanctuary. Allow the gentle rhythm of your breath to bring effortless clarity and deep serenity.',
    particleType: 'waves',
    breathingPace: 5.5,
    accent: {
      border: 'border-emerald-300/60',
      bgSelected: 'bg-emerald-400/20',
      glow: 'shadow-emerald-500/30',
      badge: 'bg-emerald-400/30 text-emerald-200 border-emerald-300/50',
      iconColor: 'text-emerald-300',
    },
    environment: {
      // Full-viewport peaceful blue/teal/emerald atmosphere
      bgBase: 'from-[#042421] via-[#094038] to-[#021816]',
      primaryGlow: 'from-emerald-400/35 via-teal-400/30 to-cyan-400/20',
      secondaryGlow: 'from-teal-300/30 via-emerald-500/25 to-transparent',
      accentRing: 'border-emerald-300/60 text-emerald-200',
      pulseColor: '#10b981',
      buttonGradient: 'from-emerald-500 via-teal-500 to-cyan-600',
      cardBorder: 'border-emerald-400/30',
      cardBg: 'bg-[#03221e]/60',
      headerBg: 'bg-[#03221e]/40',
    },
  },
  {
    id: 'sad',
    label: 'Sad',
    emoji: '😔',
    icon: CloudRain,
    altIcon: Droplets,
    statusTag: 'Gentle Harbour',
    description: 'Gentle, reflective & tender',
    message: 'It is okay to not feel okay. Give yourself gentle space and comforting grace.',
    experienceMessage: 'Sadness is a quiet invitation for tenderness. Treat yourself with deep compassion today. Just as rain nourishes the earth, gentle rest brings quiet renewal and strength.',
    particleType: 'mist',
    breathingPace: 6.0,
    accent: {
      border: 'border-sky-300/60',
      bgSelected: 'bg-sky-400/20',
      glow: 'shadow-sky-500/30',
      badge: 'bg-sky-400/30 text-sky-200 border-sky-300/50',
      iconColor: 'text-sky-300',
    },
    environment: {
      // Full-viewport deep blue/periwinkle/purple atmosphere
      bgBase: 'from-[#0a183d] via-[#16275c] to-[#06102a]',
      primaryGlow: 'from-sky-400/35 via-indigo-400/30 to-blue-500/20',
      secondaryGlow: 'from-indigo-300/25 via-sky-500/20 to-purple-500/15',
      accentRing: 'border-sky-300/60 text-sky-200',
      pulseColor: '#38bdf8',
      buttonGradient: 'from-sky-600 via-indigo-500 to-blue-600',
      cardBorder: 'border-sky-400/30',
      cardBg: 'bg-[#071333]/60',
      headerBg: 'bg-[#071333]/40',
    },
  },
  {
    id: 'angry',
    label: 'Angry',
    emoji: '😡',
    icon: Flame,
    altIcon: ShieldAlert,
    statusTag: 'Transformative Fire',
    description: 'Intense, passionate & charged',
    message: 'Channel that raw energy into grounded release and conscious clarity.',
    experienceMessage: 'Your anger carries potent protective energy. Instead of letting it scorch within, ground your feet, exhale the heat, and transmute this flame into clear, constructive power.',
    particleType: 'embers',
    breathingPace: 3.0,
    accent: {
      border: 'border-rose-400/60',
      bgSelected: 'bg-rose-500/25',
      glow: 'shadow-rose-600/40',
      badge: 'bg-rose-500/30 text-rose-200 border-rose-400/50',
      iconColor: 'text-rose-300',
    },
    environment: {
      // Full-viewport deep red/crimson/orange atmosphere
      bgBase: 'from-[#3b050b] via-[#5e0c15] to-[#290206]',
      primaryGlow: 'from-rose-500/45 via-red-500/35 to-orange-500/25',
      secondaryGlow: 'from-orange-500/30 via-rose-600/25 to-transparent',
      accentRing: 'border-rose-400/60 text-rose-200',
      pulseColor: '#f43f5e',
      buttonGradient: 'from-rose-600 via-red-600 to-orange-600',
      cardBorder: 'border-rose-400/30',
      cardBg: 'bg-[#2b0409]/60',
      headerBg: 'bg-[#2b0409]/40',
    },
  },
  {
    id: 'tired',
    label: 'Tired',
    emoji: '😴',
    icon: Moon,
    altIcon: BedDouble,
    statusTag: 'Restful Twilight',
    description: 'Drained, quiet & weary',
    message: 'Rest is restorative. Unwind your thoughts and allow your senses to recharge.',
    experienceMessage: 'You have given so much of yourself. The world can pause while you restore. Soften your jaw, relax your shoulders, and sink into this velvety dusk stillness.',
    particleType: 'stars',
    breathingPace: 7.0,
    accent: {
      border: 'border-purple-300/60',
      bgSelected: 'bg-purple-500/20',
      glow: 'shadow-purple-500/30',
      badge: 'bg-purple-400/30 text-purple-200 border-purple-300/50',
      iconColor: 'text-purple-300',
    },
    environment: {
      // Full-viewport deep violet/plum/dark-blue atmosphere
      bgBase: 'from-[#200938] via-[#351259] to-[#140424]',
      primaryGlow: 'from-purple-400/35 via-violet-500/30 to-indigo-600/20',
      secondaryGlow: 'from-fuchsia-400/25 via-purple-500/20 to-transparent',
      accentRing: 'border-purple-300/60 text-purple-200',
      pulseColor: '#c084fc',
      buttonGradient: 'from-purple-600 via-violet-600 to-indigo-600',
      cardBorder: 'border-purple-400/30',
      cardBg: 'bg-[#1b0630]/60',
      headerBg: 'bg-[#1b0630]/40',
    },
  },
  {
    id: 'energetic',
    label: 'Energetic',
    emoji: '⚡',
    icon: Zap,
    altIcon: Activity,
    statusTag: 'Kinetic Surge',
    description: 'Vibrant, dynamic & motivated',
    message: 'Unleash your momentum. Your drive and vitality are surging forward.',
    experienceMessage: 'Your frequency is electric! You are primed for creation, focus, and bold action. Channel this kinetic momentum to make meaningful strides and ignite your potential.',
    particleType: 'kinetic',
    breathingPace: 2.2,
    accent: {
      border: 'border-cyan-300/60',
      bgSelected: 'bg-cyan-400/20',
      glow: 'shadow-cyan-400/40',
      badge: 'bg-cyan-400/30 text-cyan-200 border-cyan-300/50',
      iconColor: 'text-cyan-300',
    },
    environment: {
      // Full-viewport vibrant cyan/electric/neon atmosphere
      bgBase: 'from-[#022a3d] via-[#044463] to-[#011a26]',
      primaryGlow: 'from-cyan-300/40 via-teal-300/30 to-emerald-400/25',
      secondaryGlow: 'from-yellow-300/30 via-cyan-400/25 to-blue-500/20',
      accentRing: 'border-cyan-300/60 text-cyan-200',
      pulseColor: '#22d3ee',
      buttonGradient: 'from-cyan-500 via-teal-500 to-yellow-500',
      cardBorder: 'border-cyan-400/30',
      cardBg: 'bg-[#021f2d]/60',
      headerBg: 'bg-[#021f2d]/40',
    },
  },
];
